### ISSUE TITLE
`dhms` class should be implemented

### ISSUE THREAD

**Issue by qgeissmann** [tidyverse/hms#40] opened 2017-07-25 10:52 UTC
When durations are larger than several days, the "HH:MM:SS" becomes quite hard to grasp. 
Most people will not intuitively get that "162:00:00"= "6d18:00:00". As discussed in #12. it could be very useful to provide another class, `dhms`, that displays durations in days and HMS, as well.
I am happy to implement it

**Comment by krlmlr** [comment] 2017-07-25 11:18
Thanks, this would be useful indeed.

**Comment by krlmlr** [comment] 2017-07-25 11:19
Duplicate of #14.

**Comment by krlmlr** [comment] 2021-01-13 10:45
Shelved for now.

**Closed by krlmlr** 2021-01-13 10:45 UTC
